// Code generated by "stringer --type=Mode --trimprefix=Mode --linecomment"; DO NOT EDIT.

package slog

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ModeJSON-0]
	_ = x[ModeLogFmt-1]
	_ = x[ModeColorful-2]
	_ = x[ModePlain-3]
	_ = x[ModeUndefined-99]
}

const (
	_Mode_name_0 = "jsonlogfmtcolorplain"
	_Mode_name_1 = "undefined"
)

var (
	_Mode_index_0 = [...]uint8{0, 4, 10, 15, 20}
)

func (i Mode) String() string {
	switch {
	case 0 <= i && i <= 3:
		return _Mode_name_0[_Mode_index_0[i]:_Mode_index_0[i+1]]
	case i == 99:
		return _Mode_name_1
	default:
		return "Mode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
